name: EXMNT
version: '1.0-SNAPSHOT'
main: net.hynse.eXMNT.EXMNT
api-version: '1.21'
folia-supported: true
permissions:
  exmnt.notify:
    description: Allows staff members to receive notifications about mod detections
    default: op
